version: '2.4'
services:
  mongo:
    image: mongo
    container_name: mongo
    cap_add:
      - NET_ADMIN
    ports:
      - "27017:27017"
  api:
    image: java-servlet
    container_name: java-servlet
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    mem_limit: 512mb
    depends_on:
      - mongo
